### ISSUE TITLE
global mode

### ISSUE THREAD

**Issue by fommil** [nschum/highlight-symbol.el#28] opened 2015-02-08 11:57 UTC
Hi, thanks for this package, really useful!

When I use highlight symbol I am able to highlight but not unhighlight. I need to add `highlight-symbol-mode` to the hooks for that file type.

I use this so much, I'd actually really like a global mode... can you please add a `(highlight-symbol-global-mode)` function to enable for everything? (as a workaround, adding a find-file hook always works well for this)

**Comment by nschum** [comment] 2015-04-21 21:44
Closing as a duplicate of #11.

**Closed by nschum** 2015-04-21 21:44 UTC
